import type { NextPage } from 'next'
import Head from 'next/head'
import * as $ from 'jquery'

const Home: NextPage = () => {  
    const ajaxSubmit = (e) => {
        const data = $(e.target).serialize()
        console.dir( data )
        $.ajax({
            type: 'POST',
            url: '/api/form',
            data,
            success: function(msg) {
                console.dir({
                    successMessage: msg
                })
            },
            error: function(msg) {
                console.dir({
                    errorMessage: msg
                })
            },
        })
        e.preventDefault()
        return false 
    }

    return (
        <div>
            <Head>
                <title>NextJS Forms</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />            
            </Head>

            <main>
                <h1>NextJS Forms</h1>

                <h2>Form 1 - Tradicional</h2>
                <form id="formulario-tradicional" action="/api/form" method="POST">
                    Nombre: <input type="text" name="nombre" /> <br />
                    Mensaje: <textarea name="mensaje"></textarea>
                    <br /><br />
                    <button type="submit">Enviar</button>                    
                </form>

                <h2>Form 1 - Ajax y jQuery</h2>
                <form id="formulario-ajax-jquery" action="/api/form" method="POST" onSubmit={ajaxSubmit}>
                    Nombre: <input type="text" name="nombre" /> <br />
                    Mensaje: <textarea name="mensaje"></textarea>
                    <br /><br />
                    <button type="submit">Enviar</button>                    
                </form>

            </main>
        </div>
    )
}

export default Home
